"""add pomodoro status and real duration

Revision ID: 52dbe420c39e
Revises: 
Create Date: 2026-01-15 09:35:33.743280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dbe420c39e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_cycles', sa.Column('real_duration', sa.Integer(), nullable=True))
    op.add_column('pomodoro_cycles', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_cycles', 'status')
    op.drop_column('pomodoro_cycles', 'real_duration')
    # ### end Alembic commands ###
